### ISSUE TITLE
The type or namespace Codaxy could not be found

### ISSUE THREAD

**Issue by funzeye** [codaxy/wkhtmltopdf#18]
Hi,
Ive added the nuget package into my project (aspnet 5/core mvc 6 project). I can see it in project.json file and in reference directory.
Getting this error when adding in the using statement: "using Codaxy.WkHtmlToPdf;"
Is there another step Im missing!? Does it work with latest version of asp.net?

**Comment by mstijak** [comment]
I haven't tried it with latest version of asp.net. Maybe something has changed. 

NuGet install justs copies one file to your project:
https://github.com/codaxy/wkhtmltopdf/blob/master/NuGet/Codaxy.WkHtmlToPdf/content/PdfConvert.cs

You can copy it yourself if NuGet fails again.

**Comment by funzeye** [comment]
Fair enough, thanks for reply.
