### ISSUE TITLE
Not able to run..

### ISSUE THREAD

**Issue by mahesh-dara** [codaxy/wkhtmltopdf#2]
HI, I am trying to use this codaxy for converting webforms into pdf.

I am getting the following error. Could not find the exe.

Path.Combine(OSUtil.GetProgramFilesx86Path(), @"wkhtmltopdf\wkhtmltopdf.exe")

Do I need to install some exe here? where can I find this exe? When I download the sample, I only got the tests project. Need help on this.

Thanks.

**Comment by nickkaczmarek** [comment]
should this line be in the readme? It's not immediately clear that this wrapper doesn't come with the underlying tool.
