### ISSUE TITLE
customPath null

### ISSUE THREAD

**Issue by Jedarc** [codaxy/wkhtmltopdf#21]
For some reason it is not possible to get the value for the customPath variable in the GetWkhtmlToPdfExeLocation method in the PdfConvert class.

**Comment by mstijak** [comment]
Hi, I just published a new version which doesn't require setting up any paths. You may try that.

Alternatively, you may set the path using `PdfConvert.Environment.WkHtmlToPdfPath = "...";`

**Comment by Jedarc** [comment]
I'm trying to analyze the code to create an option to generate the Pdf in memory (MemoryStream) instead of a physical file. Is this possible?

**Comment by mstijak** [comment]
Yes, simply use the `OutputStream` property. `new PdfOutput { OutputStream = targetStream }`

**Comment by Jedarc** [comment]
Thank you so much again!
But...
Is there an option that does not require the wkhtmltopdf application installed?

**Comment by mstijak** [comment]
No :)
