### ISSUE TITLE
where is the wkhtmltopdf.exe

### ISSUE THREAD

**Issue by hexuwsbg** [codaxy/wkhtmltopdf#24]
should i install wkhtmltopdf first?

**Comment by mstijak** [comment]
Yes. https://wkhtmltopdf.org/

**Comment by hexuwsbg** [comment]
@mstijak  thanks.

**Comment by Ladsers** [comment]
Maybe you should write about this in a README?

**Comment by mstijak** [comment]
Definitely. PR is welcome.
