### ISSUE TITLE
Change footer/header fonts size

### ISSUE THREAD

**Issue by SergioReis97** [codaxy/wkhtmltopdf#26]
Any way of changing the footer font size? or just include it as HTML also basicly. Other than that, great so far.

```
System.IO.Stream stream = new System.IO.MemoryStream();
            PdfConvert.ConvertHtmlToPdf(new PdfDocument {
                Url = "http://wkhtmltopdf.org/",
                HeaderLeft = "[title]",
                HeaderRight = "[date] [time]",
                FooterRight = "Oh noooooooooooooo",
                FooterLeft = "Página [page] I am really long and will eventually collide with the ",
                

            }, new PdfOutput {
                OutputStream = stream,
            });
            stream.Flush();
            stream.Position = 0;
            return new FileStreamResult(stream, "application/pdf");
```

**Comment by mstijak** [comment]
It seems that options for setting up footer font exist: https://wkhtmltopdf.org/usage/wkhtmltopdf.txt

I would gladly take a PR for this.

**Comment by SergioReis97** [comment]
Hmm I did this, also looking into the source code helped with actually seeing how the extra parameters can be use. Will try to give a little hand in documentation when I have a little freetime. Thanks

**Comment by nickkaczmarek** [comment]
this is a good example of how to use a stream and return a file. should be in the documentation.
