### ISSUE TITLE
Exception thrown: 'Codaxy.WkHtmlToPdf.PdfConvertException' 

### ISSUE THREAD

**Issue by brunoheringer** [codaxy/wkhtmltopdf#30]
Exception thrown: 'Codaxy.WkHtmlToPdf.PdfConvertException' in 'MyTest.exe'

Additional information: File 'C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe' not found. Check if wkhtmltopdf application is installed.

Is it require some install to use? I can't understood this error. Because I've used the install-package.

**Comment by mstijak** [comment]
Yes, you need to install [wkhtmltopdf](https://wkhtmltopdf.org/). This package simply invokes that tool through the command line.

**Comment by alamadcs** [comment]
but I have installed 64 bit installed
