### ISSUE TITLE
Missing information on usage

### ISSUE THREAD

**Issue by diasjoaocarlos** [codaxy/wkhtmltopdf#31]
I am using this C# converter from html to pdf.

In the .csproj I have:

  \<ItemGroup\>
    \<PackageReference Include="Codaxy.WkHtmlToPdf" Version="0.5.8" /\>
  \</ItemGroup\>

I want to use in the controller something like:

            PdfConvert.ConvertHtmlToPdf(new PdfDocument
            {
                Url = "http://wkhtmltopdf.org/",
                HeaderLeft = "[title]",
                HeaderRight = "[date] [time]",
                FooterCenter = "Page [page] of [topage]"

            }, new PdfOutput
            {
                OutputFilePath = "wkhtmltopdf-page.pdf"
            });
(this is the same code as in GitHub).

However, when I do (in the same controller):

using Codaxy.WkHtmlToPdf;

the project doesn't build (and shows error in the VS editor...). The error presented is:

Error	CS0246	The type or namespace name 'Codaxy' could not be found (are you missing a using directive or an assembly reference?)

The GitHub page of the project lacks directions on using using directive....

Could you help me?
I am using VS2019 and .Net Core 2.1

**Comment by mstijak** [comment]
Maybe Nuget installation failed. You can always manually copy this file into your project - https://github.com/codaxy/wkhtmltopdf/blob/master/NuGet/Codaxy.WkHtmlToPdf/content/PdfConvert.cs
