### ISSUE TITLE
How to use exemple

### ISSUE THREAD

**Issue by BaobabYeah** [codaxy/wkhtmltopdf#7]
Hi,

Your library is very easy to use but an little exemple is missing in the documentation.
What do you think about :

    MemoryStream memory = new MemoryStream();
    PdfOutput output = new PdfOutput() { OutputStream = memory };
    PdfConvert.ConvertHtmlToPdf(HeaderUrl, BodyUrl, FooterUrl, output);

**Comment by mstijak** [comment]
Agreed, I have added a sample to the front page.

**Comment by MikeOtown** [comment]
Where are the examples?  I only see one in readme.md.
